Migrate firewall startup/shutdown job to bicep based deployment.
retaildevcrews/ngsa-asb pull request #180
Opened 2023-02-17 16:18 UTC by gortegaMS

# Type of PR

- [x] Documentation changes
- [x] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## PR Checklist

- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My code follows the code style of this project.
- [x] I ran lint checks locally prior to submission.
- [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Purpose of PR

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Validation

- [ ] Unit tests updated and ran successfully
- [ ] Update documentation or issue referenced above

## Issues Closed or Referenced

- Closes: https://github.com/retaildevcrews/wcnp/issues/1159
- References: https://github.com/retaildevcrews/wcnp/issues/1151

2023-02-17 21:27 UTC, alfredoihernandez requested changes

2023-02-17 21:27 UTC, alfredoihernandez commented on scripts/ResourceAutomation/automationAccount.bicep
> +param firewallScheduleStartOfDayTime string='08:00:00'
can we change the timing between firewall and cluster/gateway to be more than 10 minutes? Ideally 30 to 60 minutes. Also please add item to board to investigate how chain these two together such that we don't need separate schedules.

2023-02-17 21:32 UTC, alfredoihernandez commented
can we also as part of this PR remove deprecated powershell scripts for clusters, gateway, and firewalls?

2023-02-21 16:09 UTC, alfredoihernandez commented
> can we also as part of this PR remove deprecated powershell scripts for clusters, gateway, and firewalls?

this will be done in later PRs

2023-02-21 16:09 UTC, alfredoihernandez approved these changes

2023-02-21 16:16 UTC, merged

2023-02-21 17:25 UTC, gortegaMS commented
- Manually deployed the bicep firewall deployment file from this PR
- Manually disabled the current powershell automation firewall runbooks under RG "rb-wcnp-firewall-automation-dev"
> 
![image](https://user-images.githubusercontent.com/70150605/220416403-425c1f29-6034-4d28-8541-2bd4ed51976f.png)